[package]
name = "rustCad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}
ultraviolet = "0.7"

# move these to dev-dependencies
beryllium = "0.3.0"
imagine = "0.0.5"

[dev-dependencies]